http:
  routers:
    api:
      rule: "PathPrefix(`/api`)"
      entryPoints:
        - web
      priority: 100
      service: core-go

    ui:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      priority: 1
      service: ui-node

  services:
    core-go:
      loadBalancer:
        servers:
          - url: "http://core-go:8081"

    ui-node:
      loadBalancer:
        servers:
          - url: "http://ui-node:3000"
