http:
  routers:
    ui:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      priority: 1
      service: ui-node

  services:
    ui-node:
      loadBalancer:
        servers:
          - url: "http://ui-node:3000"
